name: node
description: "elon-2 gh-issue"
assignees: "diogobaltazar"
projects: ["projects/2"]
body:
  - type: textarea
    id: about
    attributes:
      label: About
      description: Node description
    validations:
      required: true

  - type: textarea
    id: value
    attributes:
      label: Value
      placeholder: The value that the node is providing overall
    validations:
      required: true

  - type: textarea 
    id: neighbours
    attributes:
      label: neighbours
      placeholder: List the IDs of the children
    validations:
      required: false

- type: checkboxes
  id: dod
  attributes:
    label: Definition-of-done
    description: You may select more than one.
    options:
      - label: Orange cat (required. Everyone likes orange cats.)
        required: true
      - label: **Black cat**
