name: node
description: "elon-2 gh-issue"
assignees: "diogobaltazar"
projects: ["projects/2"]
body:
  - type: textarea
    id: about
    attributes:
      label: About
      description: Node description
    validations:
      required: true

  - type: textarea
    id: value
    attributes:
      label: Value
      placeholder: The value that the node is providing overall
    validations:
      required: true

  - type: textarea 
    id: neighbours
    attributes:
      label: Neighbours
      description: |
        Neighbouring nodes
        Add from suffixes:
        - `[dep]`: the neighbour is a dependency
        - `[parent]`: the neighbour is a parent
        - `[child]`: the node is a child
      placeholder: List the neighbour nodes by `gh-issue-id`
    validations:
      required: false

  - type: textarea
    id: ac
    attributes:
      label: Acceptance Criteria
      description: Complete where it applies, add node specific `ac`.
      value: 
    validations:
      required: true

  - type: checkboxes
    id: dod
    attributes:
      label: Definition of done
      description: Complete where it applies, add node specific `dod`.
      options:
        - label: `Code Complete`: The code for the user task is fully written and checked into the version control system.
    validations:
      required: true

