name: node
description: "elon-2 gh-issue"
assignees: "diogobaltazar"
projects: ["projects/2"]
body:
  - type: textarea
    id: about
    attributes:
      label: About
      description: Node description
    validations:
      required: true

  - type: textarea
    id: value
    attributes:
      label: Value
      placeholder: The value that the node is providing overall
    validations:
      required: true

  - type: textarea
    id: neighbours
    attributes:
      label: Neighbours
      description: |
        Neighbouring nodes
        Add from suffixes:
        - `[dep]`: the neighbour is a dependency
        - `[parent]`: the neighbour is a parent
        - `[child]`: the node is a child
      placeholder: List the neighbour nodes by `gh-issue-id`
    validations:
      required: false

  - type: textarea
    id: ac
    attributes:
      label: Acceptance Criteria
      description: Complete where it applies, add node specific `ac`.
      value:
    validations:
      required: true

  - type: checkboxes
    id: dod
    attributes:
      label: Definition of done
      options:
        - label: code-complete
        - label: code-reviewed
        - label: unit-tests
        - label: integration-tests
        - label: functional-tests
        - label: docs
        - label: known-bugs
        - label: sandbox-deploy
      description: |
        Complete where it applies:
        - label: `code-complete` The code for the user task is fully written and checked into the version control system.
        - label: `code-reviewd` The code has been reviewed by another team member, and any necessary changes have been made.
        - label: `unit-tests` Unit tests have been written for the new code, and all tests are passing.
        - label: `integration-tests` The code integrates correctly with the existing system, and any integration tests are passing.
        - label: `functional-tests` The user task has been tested against its acceptance criteria, and it meets the expected functionality.
        - label: `docs` Any necessary documentation has been updated or completed. This could include inline code comments, external technical documentation, or end-user documentation.
        - label: `known-bugs` The task does not have any known bugs or if it does, they have been properly captured in a separate issue, if not fixed;
        - label: `sandbox-deploy` The code has been deployed to a staging environment that closely resembles production.
    validations:
      required: true

