name: node
description: "elon-2 gh-issue"
assignees: "diogobaltazar"
projects: ["projects/2"]
description: "Read the README below for more information"
body:
  - type: textarea
    id: about
    attributes:
      label: About
    validations:
      required: true

  - type: textarea
    id: value
    attributes:
      label: Value
      placeholder: The value that the node is providing overall
    validations:
      required: true

  - type: textarea
    id: neighbours
    attributes:
      label: Neighbours
      placeholder: List the neighbour nodes by `gh-issue-id`
    validations:
      required: false

  - type: textarea
    id: ac
    attributes:
      label: Acceptance Criteria
      placeholder: acceptance checklist
    validations:
      required: true

  - type: checkboxes
    id: dor
    attributes:
      label: Definition of Ready
      options:
        - label: (AC1) clear-acceptance-criteria
          required: true
        - label: (AC2) business-value
          required: true
        - label: (AC3) no-dependencies
          required: true
        - label: (AC4) no-blockers
          required: true
        - label: (AC5) feasibility-assessed
          required: true
        - label: (AC6) resource-availability
          required: true
        - label: (AC7) prioritization
          required: true
        - label: (AC8) small-enough
          required: true
        - label: (AC9) clarity
          required: true
        - label: (AC10) milestone
          required: true
        - label: (AC11) iteration
          required: true
        - label: (AC12) ownership
          required: true
    validations:
      required: true

  - type: checkboxes
    id: dod
    attributes:
      label: Definition of done
      options:
        - label: (DOD1) code-complete
          required: true
        - label: (DOD2) code-reviewed
          required: true
        - label: (DOD3) unit-tests
          required: true
        - label: (DOD4) integration-tests
          required: true
        - label: (DOD5) functional-tests
          required: true
        - label: (DOD6) docs
          required: true
        - label: (DOD7) known-bugs
          required: true
        - label: (DOD8) sandbox-deploy
          required: true
    validations:
      required: true

  - type: markdown
    id: readme
    attributes:
      value: |
        # README

        ## Neighbouring nodes
        
        Add from suffixes:

        - `[dep]`: the neighbour is a dependency
        - `[parent]`: the neighbour is a parent
        - `[child]`: the node is a child

        ## AC - Acceptance Criteria

        Define the criteria (checklist) that must be met for the task to be considered `Done`. The criteria must be `SMART`, *i.e.*:

        - `specific`
        - `measurable`
        - `achievable`
        - `relevant`
        - `time-bound`

        ## DoR - Defition of Ready

        - (AC1) `clear-acceptance-criteria`: The user task must have specific acceptance criteria that define the boundary of the task’s requirements and how they will be verified.
        - (AC2) `business-value`: The task must deliver a clear value to the user or customer.
        - (AC3) `no-dependencies`: Any dependencies on other stories or external factors have been identified and resolved or have a clear plan for resolution.
        - (AC4) `no-blockers`: There are no blockers that prevent the task from being worked on.
        - (AC5) `feasibility-assessed`: The technical feasibility has been assessed, and any significant architectural concerns have been addressed.
        - (AC6) `resource-availability`: The necessary resources (personnel, environments, tools, etc.) are available to work on the task.
        - (AC7) `prioritization`: The task is prioritized in the backlog and scheduled for an upcoming sprint.
        - (AC8) `small-enough`: The task is small enough to be completed in one iteration, adhering to the team's past velocity and capacity.
        - (AC9) `clarity`: The team has a clear understanding of what is expected and there is no ambiguity in the task.
        - (AC10) `milestone`: The task has been assigned a milestone
        - (AC11) `iteration`: The task has been assigned a a milestone iteration
        - (AC112) `ownership`: The task has assigned ownership to a team member

        ## DoD - Definition of Done

        - (DOD1) `code-complete` The code for the user task is fully written and checked into the version control system.
        - (DOD2) `code-reviewd` The code has been reviewed by another team member, and any necessary changes have been made.
        - (DOD3) `unit-tests` Unit tests have been written for the new code, and all tests are passing.
        - (DOD4) `integration-tests` The code integrates correctly with the existing system, and any integration tests are passing.
        - (DOD5) `functional-tests` The user task has been tested against its acceptance criteria, and it meets the expected functionality.
        - (DOD6) `docs` Any necessary documentation has been updated or completed. This could include inline code comments, external technical documentation, or end-user documentation.
        - (DOD7) `known-bugs` The task does not have any known bugs or if it does, they have been properly captured in a separate issue, if not fixed;
        - (DOD8) `sandbox-deploy` The code has been deployed to a staging environment that closely resembles production.
  
