name: node
title: "[node]: "
description: "Create a new node"
labels: "enhancement"
assignees: "diogobaltazar"
projects: ["diogo"]
body:
  - type: markdown
    attributes:
      value: |
        Node Issue

  - type: textarea
    id: about
    attributes:
      label: About
      placeholder: Describe what the issue is about
    validations:
      required: true

  - type: textarea
    id: value
    attributes:
      label: Business Value
      placeholder: Describe the business value the feature is enabling
    validations:
      required: true

  - type: textarea 
    id: neighbours
    attributes:
      label: neighbours
      placeholder: List the IDs of the children
    validations:
      required: false

  - type: textarea
    id: dependencies
    attributes:
      label: Dependencies
      placeholder: List the issues on which this issue depends
    validations:
      required: false

  - type: textarea
    id: dod
    attributes:
      label: Definition of done
      placeholder: List the conditions of the definition of done
    validations:
      required: false
